name: Update progress graph and JSON

on: 
  push:
    branches:
      - main

jobs:
  update-graphs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r utils/requirements.txt

      - name: Run check_progress.py
        run: python utils/check_progress.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "Chore: Update progress graphs [skip ci]"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}